### PR TITLE
#47 Adding GitHub Actions CI

### PR DESCRIPTION
**Pull request by gunnarmorling**
Hey @osheroff, this should all that's needed for building and running tests against MySQL 5.7 and 8.0 upon PR submission and pushes to master. Do we still need the CircleCI config or can I remove that?

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Btw. this PR itself won't trigger the build runs yet, this will only be the case for the next PR once this has been merged.

**Comment by wingerx** [comment]
Hi, @gunnarmorling
Should we think about use test-containers  in run test usecase? And i am also interesting in this, I think test-containers can be very easy to run integration test and reduce the cost of unit testing

**Comment by gunnarmorling** [comment]
Hey @osheroff, so I moved forward and merged this change, it shouldn't have any negative impact. I hope that's ok?

**Comment by osheroff** [comment]
👍 been in iceland for about exactly 12 days.  no need to wait for me on small stuff like this, that's why I gave you commit access :)

**Pull request merged**
