### PR TITLE
Support MySQL 8.4 changes

### LINKED ISSUE #147: MySQL 8.4 removed "Show master status" SQL command
https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html

According to the MySQL release notes for MySQL 8.4 they just removed a bunch of SQL commands

>SQL statements removed.  The following SQL statements have been removed (replacements in brackets): START SLAVE ([START REPLICA](https://dev.mysql.com/doc/refman/8.4/en/start-replica.html)); STOP SLAVE ([STOP REPLICA](https://dev.mysql.com/doc/refman/8.4/en/stop-replica.html)); SHOW SLAVE STATUS ([SHOW REPLICA STATUS](https://dev.mysql.com/doc/refman/8.4/en/show-replica-status.html)); SHOW SLAVE HOSTS ([SHOW REPLICAS](https://dev.mysql.com/doc/refman/8.4/en/show-replicas.html)); RESET SLAVE (RESET REPLICA); CHANGE MASTER TO ([CHANGE REPLICATION SOURCE TO](https://dev.mysql.com/doc/refman/8.4/en/change-replication-source-to.html)); RESET MASTER ([RESET BINARY LOGS AND GTIDS](https://dev.mysql.com/doc/refman/8.4/en/reset-binary-logs-and-gtids.html)); SHOW MASTER STATUS ([SHOW BINARY LOG STATUS](https://dev.mysql.com/doc/refman/8.4/en/show-binary-log-status.html)); PURGE MASTER LOGS ([PURGE BINARY LOGS](https://dev.mysql.com/doc/refman/8.4/en/purge-binary-logs.html)); and SHOW MASTER LOGS ([SHOW BINARY LOGS](https://dev.mysql.com/doc/refman/8.4/en/show-binary-logs.html)).

> The statements just listed have also been removed from all MySQL test programs and files, and elsewhere, where used internally.

That leads to `com.github.shyiko.mysql.binlog.network.ServerException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'master status' at line 1` while trying to initialize

### PR DESCRIPTION
**Pull request by Naros**
Updates MySQL binlog client for changes with https://github.com/debezium/debezium/pull/5549

Fixes #147

### CODE REVIEW

**Comment by Naros** [comment]
Opened changes https://github.com/debezium/mysql-binlog-connector-java, which is where we will be maintaining this moving forward.

**Comment by Naros** [comment]
Hi @osheroff, we're not yet in a position to cut a release based on Debezium's organization.  Would you be able to cut one final release of this artifact for us?  I've applied two commits, the behavior change to support 8.4 & bumped the version details.  Let me know if that's possible.

**Comment by EeshwarPrasath** [comment]
Is the support for 8.4 now available? @Naros

**Comment by osheroff** [comment]
@Naros ok released.  Please let me know when y'all have finished your fork, i'm happy to re-point this repo over there

**Pull request closed without merging**
