### PR TITLE
Handle YEAR as numeric for metadata processing

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by osheroff** [comment]
can you write a test for this?

**Comment by jpechane** [comment]
@osheroff I am trying to add a new method to `BinaryLogClientIntegrationTest`. Unfortunately the emitted events do not contain event metadata, see
```
NFO: Received Event{header=EventHeaderV4{timestamp=1686812421000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=55, nextPosition=2542, flags=0}, data=TableMapEventData{tableId=219, database='mbcj_test', table='data_type_hell', columnTypes=3, 13, 3, 3, 3, 3, 3, 3, 3, -2, columnMetadata=0, 0, 0, 0, 0, 0, 0, 0, 0, 65054, columnNullability={1, 2, 3, 4, 5, 6, 7, 8, 9}, eventMetadata=null}}
```
Those are necessary for bug reproduction. Do you know why is that, what setting is necessary to be set so the metadata are present?

**Comment by jpechane** [comment]
@osheroff Test added, requires `MYSQL_VERSION=8.0` to see failure on unfixed codebase.

**Comment by aprakash-work** [comment]
Curious if there is a timeline for this fix?

**Comment by linleicheng** [comment]
waiting for this patch

**Pull request merged**
